using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

namespace SteeringBehaviours
{
    public class AIAgent : MonoBehaviour
    {
        public float maxSpeed = 10f;
        public float maxDistance = 5f;
        public bool updatePosition = true;
        public bool updateRotation = true;
        public Vector3 velocity;

        private Vector3 force;
        private List<SteeringBehaviour> behaviours;
        private NavMeshAgent agent;

        private void Awake()
        {
            
        }
        private void Update()
        {
            
        }
        //Calculate all the forces generated by each attached SteeringBehaviour
        private void ComputeForces()
        {

        }
        //Apply the total velocity to the AIAgent
        private void ApplyVelocity()
        {

        }
    }
}
